Feat/api metrics issue 13
Heptagram-Project/api pull request #123
Opened 2022-09-17 15:27 UTC by satyap54

# Pull Request

## Description

## Related Issue

Closes #13 

## 6.0.1

Did you remember to update the version number in the package.json file?

- [x] For a major restructuring, or large changes please bump the the major version number. (ex: 1.x.x)
- [ ] For a minor change, bump the minor version number. (ex: x.1.x)
- [ ] For a bug fix, bump the patch version number. (ex: x.x.1)

## Documentation

For _any_ version updates, please verify if the [documentation page]() needs an update. If it does, please [uptade the in code docs]() to ensure it is not forgotten.

- [x] My contribution does NOT require a documentation update.
- [ ] My contribution DOES require a documentation update.

2022-09-18 18:12 UTC, j-dogcoder requested changes

2022-09-18 18:12 UTC, j-dogcoder commented on src/routes/api.ts
> +router.use("/metrics", metricsRoutes);
Please Document Metrics Routes

2022-09-19 04:20 UTC, satyap54 commented on src/index.ts
> +  const application = app.listen(PORT, () => {
But, this doesn't seem to be an async operation. Do you still need it?

2022-09-19 06:10 UTC, satyap54 commented on src/routes/api.ts
> +router.use("/metrics", metricsRoutes);
Added

2022-09-19 11:53 UTC, j-dogcoder commented on src/index.ts
> +  const application = app.listen(PORT, () => {
yes

2022-09-19 12:45 UTC, satyap54 commented on src/index.ts
> +  const application = app.listen(PORT, () => {
ok, added

2022-09-21 11:26 UTC, satyap54 commented
Hi @j-dogcoder , any update on this PR?

2022-09-21 11:31 UTC, satyap54 commented
No, you can merge it if testing goes well.

2022-09-21 11:39 UTC, j-dogcoder submitted a review, later dismissed

2022-09-21 11:40 UTC, merged