Added random number generator
Heptagram-Project/api pull request #142
Opened 2022-10-04 20:24 UTC by Sukriti-m

# Pull Request

## Description
Added random number generator

## Related Issue

Closes #140 

## Version

Did you remember to update the version number in the package.json file?

- [ ] For a major restructuring, or large changes please bump the the major version number. (ex: 1.x.x)
- [x] For a minor change, bump the minor version number. (ex: x.1.x)
- [ ] For a bug fix, bump the patch version number. (ex: x.x.1)

I am open to suggestions and changes.
@j-dogcoder  Please merge my PR and add the 'hacktoberfest-accepted' label to the PR.

2022-10-04 20:48 UTC, j-dogcoder requested changes
We should not have a package-lock.json, please delete it

2022-10-05 03:38 UTC, Sukriti-m commented
> We should not have a package-lock.json, please delete it

I have made the required changes. Please review it,

2022-10-05 19:01 UTC, j-dogcoder requested changes

2022-10-05 19:02 UTC, j-dogcoder commented
Also, please update your branch and resolve the merge conflicts.

2022-10-05 19:03 UTC, j-dogcoder commented
We do also need the package.json version number to be bumped. It should be `7.2.0` after this PR

2022-10-09 12:06 UTC, Sukriti-m commented on src/routes/api/randomnumber.ts
> +import { v4 as uuidv4 } from "uuid";
I have resolved it.Please check once

2022-10-09 12:17 UTC, j-dogcoder approved these changes

2022-10-09 12:17 UTC, j-dogcoder commented
LGTM

2022-10-09 12:17 UTC, merged

2022-10-09 12:18 UTC, j-dogcoder commented
### 🎉 Congratulations @Sukriti-m! 🎉 

Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labeled `help wanted` for additional opportunities to contribute.

**Discord Server:**
_We would love it if you joined our community discord server! Your contribution to the project make you eligible for special roles & perks._